### ISSUE TITLE
Grazie

### ISSUE THREAD

**Issue by eliseomartelli** [91DarioDev/iliadbot#10]
Grazie per questo bot!
Posso prendermi la libertà di astrarre il crawler in una libreria separata? Vorrei aggiungere un sensore per vedere i dati da Iliad su http://GitHub.com/home-assistant/home-assistant 👌

**Comment by makovez** [comment]
Sarebbe fantastico ;)

Il giorno Mer 26 Dic 2018, 16:43 Eliseo Martelli <notifications@github.com>
ha scritto:

**Comment by makovez** [comment]
Ovviamente rispettando la licenza.

Il giorno Mer 26 Dic 2018, 17:23 Namoso ErMejo <namosoermejo@gmail.com> ha
scritto:

**Comment by 91DarioDev** [comment]
Ciao, sì non c'è problema. La licenza dovrebbe permetterlo 😊

**Comment by giovanniacanforah** [comment]
la licenza lo permette? bene, si.

**Comment by eliseomartelli** [comment]
Eccola :) https://github.com/eliseomartelli/AioIliad
Fammi sapere cosa ne pensi!
